language: r
sudo: required
cache: packages

env:
  _R_CHECK_FORCE_SUGGESTS_=false
  R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

before_install:
- openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv
  -in tests/testthat/abbyy_key.enc -out tests/testthat/abbyy_key -d

# Only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: always