language: r
sudo: required

warnings_are_errors: true

r_binary_packages:
  - BH
  - NLP
  - Rcpp
  - assertthat
  - digest
  - dplyr
  - knitr
  - rmarkdown
  - stringr
  - testthat
  - tidyr
  - ipred

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: always